### ISSUE TITLE
Testing text2tif on Windows with MinGW(-w64)

### ISSUE THREAD

**Issue by amitdo** [amitdo/text2tif#1]
Someone needs to test it...

**Comment by amitdo** [comment]
@Shreeshrii,
Could you test it?

First thing you should do is to tell me is if you succeed to compile it.

**Comment by Shreeshrii** [comment]
I have just removed msys2 setup from my PC. Will reinstall and test.

ShreeDevi

---

भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by amitdo** [comment]
OK, Thanks :-)

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ g++ -o text2tif -std=c++11 -g -Wall -Wno-sign-compare -Wno-uninitialized -O0 -DDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE ./port/strcasestr.cpp ./training/boxchar.cpp ./training/commandlineflags.cpp ./training/degradeimage.cpp ./training/fileio.cpp ./training/ligature_table.cpp ./training/normstrngs.cpp ./training/pango_font_info.cpp ./training/stringrenderer.cpp ./training/tessopt.cpp ./training/text2image.cpp ./training/tlog.cpp ./ccutil/ccutil.cpp ./ccutil/errcode.cpp ./ccutil/memry.cpp ./ccutil/params.cpp ./ccutil/scanutils.cpp ./ccutil/serialis.cpp ./ccutil/strngs.cpp ./ccutil/tprintf.cpp ./ccutil/unichar.cpp ./ccutil/unicharmap.cpp ./ccutil/unicharset.cpp -lm -pthread -llept -I/usr/local/include/leptonica -I./port -I./training -I./ccutil `pkg-config --cflags --libs icu-i18n` `pkg-config --cflags --libs pango` `pkg-config --cflags --libs cairo` `pkg-config --cflags --libs pangocairo` `pkg-config --cflags --libs fontconfig` `pkg-config --cflags --libs freetype2` `pkg-config --cflags --libs pangoft2`
./training/pango_font_info.cpp: In member function 'bool tesseract::PangoFontInfo::ParseFontDescription(const PangoFontDescription*)':
./training/pango_font_info.cpp:223:46: error: 'strcasestr' was not declared in this scope
   is_fraktur_ = (strcasestr(family, "Fraktur") != NULL);
                                              ^
./ccutil/scanutils.cpp: In function 'int tvfscanf(FILE*, const char*, va_list)':
./ccutil/scanutils.cpp:289:7: warning: variable 'sign' set but not used [-Wunused-but-set-variable]
   int sign;
       ^

```

**Comment by amitdo** [comment]
We are testing:
1) Linux - Lubuntu
2) Windows, Cygwin
3) Windows, MinGW-w64

I suggest we focus testing on one platform and environment. After we'll finish with it we can move to another platform and environment.

The easiest one is Lubuntu. Let focus on it first.

BTW, do you dual-boot or you are running Windows in VM?

**Comment by Shreeshrii** [comment]
Yesterday I replaced Windows 7 on my netbook with lubuntu.

lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu Xenial Xerus (development branch)
Release:    16.04
Codename:    xenial

I had a cygwin setup on a laptop with Windows 10 from sometime back. I
updated that yesterday. and I installed msys2 on the same laptop now. It is
not dual boot, I run the shell while running windows.

I will focus the tests on lubuntu.

ShreeDevi

---

भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
Error while compiling:

```
ra@Shree MINGW64 ~/text2tif
$ git log -2
commit b59c24c74f6f1a8834076c767f09096182924fc4

    Alternative strcasestr() only needed on Windows

commit 3c2ab3af46fe9068e001ae44e1b6aeb3b0e40a7d

    README.md, 'Compiling' section: Add '-Wno-sign-compare'

ra@Shree MINGW64 ~/text2tif
$ g++ -o text2tif -std=c++11 -g -Wall -Wno-sign-compare -Wno-uninitialized -O0 -DDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE ./port/strcasestr.cpp ./training/boxchar.cpp ./training/commandlineflags.cpp ./training/degradeimage.cpp ./training/fileio.cpp ./training/ligature_table.cpp ./training/normstrngs.cpp ./training/pango_font_info.cpp ./training/stringrenderer.cpp ./training/tessopt.cpp ./training/text2image.cpp ./training/tlog.cpp ./ccutil/ccutil.cpp ./ccutil/errcode.cpp ./ccutil/memry.cpp ./ccutil/params.cpp ./ccutil/scanutils.cpp ./ccutil/serialis.cpp ./ccutil/strngs.cpp ./ccutil/tprintf.cpp ./ccutil/unichar.cpp ./ccutil/unicharmap.cpp ./ccutil/unicharset.cpp -lm -pthread -llept -I/usr/local/include/leptonica -I./port -I./training -I./ccutil `pkg-config --cflags --libs icu-i18n` `pkg-config --cflags --libs pango` `pkg-config --cflags --libs cairo` `pkg-config --cflags --libs pangocairo` `pkg-config --cflags --libs fontconfig` `pkg-config --cflags --libs freetype2` `pkg-config --cflags --libs pangoft2`

./training/pango_font_info.cpp: In member function 'bool tesseract::PangoFontInfo::ParseFontDescription(const PangoFontDescription*)':
./training/pango_font_info.cpp:223:46: error: 'strcasestr' was not declared in this scope
   is_fraktur_ = (strcasestr(family, "Fraktur") != NULL);
                                              ^
./ccutil/scanutils.cpp: In function 'int tvfscanf(FILE*, const char*, va_list)':
./ccutil/scanutils.cpp:289:7: warning: variable 'sign' set but not used [-Wunused-but-set-variable]
   int sign;

```

**Comment by amitdo** [comment]
I pushed a new commit, please try it.

**Comment by Shreeshrii** [comment]
Compiled ok. 
seg fault when called without parameter. 
--help works

```
./ccutil/scanutils.cpp: In function 'int tvfscanf(FILE*, const char*, va_list)':
./ccutil/scanutils.cpp:289:7: warning: variable 'sign' set but not used [-Wunused-but-set-variable]
   int sign;
       ^

ra@Shree MINGW64 ~/text2tif
$ ./text2tif
Segmentation fault

ra@Shree MINGW64 ~/text2tif
$ ./text2tif --help
USAGE: C:\msys64\home\ra\text2tif\text2tif.exe
  --tlog_level  Minimum logging level for tlog() output  (type:int default:0)
  --exposure  Exposure level in photocopier  (type:int default:0)

```

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --list_available_fonts
  0: AR BERKLEY
  1: AR BLANCA
  2: AR BONNIE
  3: AR CARTER
  4: AR CENA
etc
```

**Comment by amitdo** [comment]
Shree,

Could you tell me, with the various **Tesseract** 3.04 training tools, what things are not working in cygwin and mingw ?

**Comment by amitdo** [comment]
I mean, if you try to train Tesseract according to the guide in the wiki, what commands are not working?

**Comment by Shreeshrii** [comment]
There were seg faults for text2image with various options. I think others work fine. I'll test with a sample and get back later.

**Comment by amitdo** [comment]
Just to clarify, I don't ask you to retest Tesseract training tools now...

**Comment by amitdo** [comment]
> Just to clarify, I don't ask you to retest Tesseract training tools now...

I didn't see your reply above.
Anyway, if it's too much work for you, don't test Tesseract.

Thanks for all the testing!

**Comment by Shreeshrii** [comment]
It has been a while since I did tesseract training and testing. 

Lastly I was using a modified version of tesstrain.sh (old version) - skipping the image and box file genration. I used box tif pairs generated by jtessboxeditor and ran rest of the script after that. 

Some suggestions re training:

The new tesstrain, has language specific font list. There should be a check to see that those fonts exist on the system before running the training. Program shouldn't die, either give a msg and skip font, or check in bash itself and then  create a temp font list with available fonts to use for the run.

**Comment by Shreeshrii** [comment]
Another suggestion : re tesstrain.sh, add an option to only create box tif pairs, also another to run training from existing box tif pairs.

**Comment by amitdo** [comment]
Good suggestions.
I don't know bash scripting, so I can't help with that.

**Comment by Shreeshrii** [comment]
Mingw64 package for tesseract was compiled without debug. I am now getting errors while trying to compilie it (without using PKGBUILD).
```

ra@Shree MINGW64 ~/tesseract
$ make
make  all-recursive
make[1]: Entering directory '/home/ra/tesseract'
Making all in ccutil
make[2]: Entering directory '/home/ra/tesseract/ccutil'
make[3]: Entering directory '/home/ra/tesseract/ccutil'
depbase=`echo ambigs.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2 -DNDEBUG   -I/usr/local/include/leptonica -mms-bitfields -IC:/msys64/mingw64/include/pango-1.0 -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -mms-bitfields -IC:/msys64/mingw64/include/cairo -IC:/msys64/mingw64/include/pixman-1 -IC:/msys64/mingw64/include -I/mingw64/include/freetype2 -I/mingw64/include/libpng16 -I/mingw64/include/harfbuzz -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include/libpng16 -DTESSDATA_PREFIX=/usr/local/share/  -g -O2 -std=c++11 -MT ambigs.lo -MD -MP -MF $depbase.Tpo -c -o ambigs.lo ambigs.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I/usr/local/include/leptonica -mms-bitfields -IC:/msys64/mingw64/include/pango-1.0 -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -mms-bitfields -IC:/msys64/mingw64/include/cairo -IC:/msys64/mingw64/include/pixman-1 -IC:/msys64/mingw64/include -I/mingw64/include/freetype2 -I/mingw64/include/libpng16 -I/mingw64/include/harfbuzz -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include/libpng16 -DTESSDATA_PREFIX=/usr/local/share/ -g -O2 -std=c++11 -MT ambigs.lo -MD -MP -MF .deps/ambigs.Tpo -c ambigs.cpp  -DDLL_EXPORT -DPIC -o .libs/ambigs.o
ambigs.cpp:31:22: fatal error: strtok_r.h: No such file or directory
compilation terminated.
Makefile:572: recipe for target 'ambigs.lo' failed
make[3]: *** [ambigs.lo] Error 1
make[3]: Leaving directory '/home/ra/tesseract/ccutil'
Makefile:614: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/ra/tesseract/ccutil'
Makefile:470: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ra/tesseract'
Makefile:378: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by amitdo** [comment]
Did you run:

```
./autogen.sh
./configure  --enable-debug
```

**Comment by amitdo** [comment]
https://github.com/Alexpux/MINGW-packages/blob/0c6b2f6/mingw-w64-tesseract-ocr/PKGBUILD#L35

**Comment by Shreeshrii** [comment]
Zdenko suggested a change in configure.ac and it is working now:

> > please try to change mingw32_) to mingw_) in configure.ac (line 78?) and
> > then rebuild autotools (./autogen.sh ...)

ShreeDevi

---

भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
Getting back to testing text2tif on mingw64
Does not seem to give debug info

```
ra@Shree MINGW64 ~/text2tif
$ ./text2tif
Segmentation fault
ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/ara/ara.training_text --font FreeZerif --outputbase ara.FreeSerif.exp0
Segmentation fault

ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/eng/eng.training_text --font Arial --outputbase eng.Arial.exp0
Segmentation fault

ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/eng/eng.training_text  --outputbase eng.Arial.exp0
Segmentation fault

ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fontconfig_refresh_cache
Segmentation fault

ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/san/san.training_text --fontconfig_refresh_cache
Segmentation fault

ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/san/san.training_text --outputbase san.exp-1 --ptsize=32 --strip_unrenderable_words --fontconfig_refresh_config_file=false --leading=32 --char_spacing=0.0 --exposure=-1 --find_fonts --min_coverage=.9 --degrade_image=1 --underline_start_prob=.05 --underline_continuation_prob=.01
WARNING: Could not find a font to render image title with!
Total chars = 57894
Font AR BERKLEY failed with 8168 hits = 14.11%
Font AR BLANCA failed with 8168 hits = 14.11%
Font AR BONNIE failed with 8168 hits = 14.11%
Font AR CARTER failed with 8168 hits = 14.11%

```

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ gdb ./text2tif
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./text2tif...done.
(gdb) run --fonts_dir= --text ../langdata/ara/ara.training_text --font FreeZerif --outputbase ara.FreeSerif.exp0
Starting program: C:\msys64\home\ra\text2tif\text2tif.exe --fonts_dir= --text ../langdata/ara/ara.training_text --font FreeZerif --outputbase ara.FreeSerif.exp0
[New Thread 6064.0x1e68]
[New Thread 6064.0x1700]
[New Thread 6064.0x1668]
[New Thread 6064.0x212c]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000000041060f in ERRCODE::error (this=0x45d7b0 <_ZL13ASSERT_FAILED>,
    caller=0x4499b2 <kRandomSeed+1194> "", action=ABORT,
    format=0x449832 <kRandomSeed+810> "in file %s, line %d")
    at ./ccutil/errcode.cpp:86
86            if (!*p)
(gdb) stack
Undefined command: "stack".  Try "help".
(gdb) backtrace
#0  0x000000000041060f in ERRCODE::error (this=0x45d7b0 <_ZL13ASSERT_FAILED>,
    caller=0x4499b2 <kRandomSeed+1194> "", action=ABORT,
    format=0x449832 <kRandomSeed+810> "in file %s, line %d")
    at ./ccutil/errcode.cpp:86
#1  0x000000000040e2f5 in main (argc=1, argv=0x44599a8)
    at ./training/text2image.cpp:437
(gdb) exit
Undefined command: "exit".  Try "help".
(gdb) quit
A debugging session is active.

        Inferior 1 [process 6064] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]

```

**Comment by amitdo** [comment]
> Getting back to testing text2tif on mingw64
> Does not seem to give debug info

What about text2image ?

**Comment by amitdo** [comment]
https://groups.google.com/forum/?hl=en#!topic/tesseract-issues/IWL-ZH7-3UY

> But gives seg fault in the following:
> 
> $ text2image
> Segmentation fault 

and...

> running it from command prompt gives the following error
> 
> Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.
>   text2image
> Text file missing!
> !FLAGS_text.empty():Error:Assert failed:in file  
> C:/git/mingw/mingw-w64-tesseract-ocr/src/tesseract-ocr-298e31465a44/training/text2image.cpp,  
> line 428

**Comment by Shreeshrii** [comment]
Yes, that was from my earlier testing in 2014.

ShreeDevi

---

भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by amitdo** [comment]
Did you try running text2tif from command prompt?

**Comment by amitdo** [comment]
I pushed some commits to the repo...

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ git log -2
commit 3c718268618eb76f6b7ff5ca58e261283ebf4b16
Date:   Fri Mar 25 01:18:42 2016 +0200

    Print help message when (argv == 1) [Take II]

    In training/commandlineflags.cpp

commit 508222d09f2cf3d8214b42324a598a20cf2b1500
Date:   Fri Mar 25 00:52:37 2016 +0200

    Print help message when (argv == 1)

    In training/commandlineflags.cpp

```

```
ra@Shree MINGW64 ~/text2tif
$ ./text2tif
USAGE: C:\msys64\home\ra\text2tif\text2tif.exe
  --tlog_level  Minimum logging level for tlog() output  (type:int default:0)
  --exposure  Exposure level in photocopier  (type:int default:0)
  --resolution  Pixels per inch  (type:int default:300)
  --xsize  Width of output image  (type:int default:3600)
  --ysize  Height of output image  (type:int default:4800)
  --margin  Margin round edges of image  (type:int default:100)
  --ptsize  Size of printed text  (type:int default:12)
  --leading  Inter-line space (in pixels)  (type:int default:12)
  --box_padding  Padding around produced bounding boxes  (type:int default:0)
  --glyph_resized_size  Each glyph is square with this side length in pixels  (type:int default:0)
  --glyph_num_border_pixels_to_pad  Final_size=glyph_resized_size+2*glyph_num_border_pixels_to_pad  (type:int default:0)
  --char_spacing  Inter-character space in ems  (type:double default:0)
  --underline_start_prob  Fraction of words to underline (value in [0,1])  (type:double default:0)
  --underline_continuation_prob  Fraction of words to underline (value in [0,1])  (type:double default:0)
  --min_coverage  If find_fonts==true, the minimum coverage the font has of the characters in the text file to include it, between 0 and 1.  (type:double default:1)
  --degrade_image  Degrade rendered image with speckle noise, dilation/erosion and rotation  (type:bool default:true)
  --strip_unrenderable_words  Remove unrenderable words from source text  (type:bool default:true)
  --ligatures  Rebuild and render ligatures  (type:bool default:false)
  --find_fonts  Search for all fonts that can render the text  (type:bool default:false)
  --render_per_font  If find_fonts==true, render each font to its own image. Image filenames are of the form output_name.font_name.tif  (type:bool default:true)
  --list_available_fonts  List available fonts and quit.  (type:bool default:false)
  --render_ngrams  Put each space-separated entity from the input file into one bounding box. The ngrams in the input file will be randomly permuted before rendering (so that there is sufficient variety of characters on each line).  (type:bool default:false)
  --output_word_boxes  Output word bounding boxes instead of character boxes. This is used for Cube training, and implied by --render_ngrams.  (type:bool default:false)
  --bidirectional_rotation  Rotate the generated characters both ways.  (type:bool default:false)
  --only_extract_font_properties  Assumes that the input file contains a list of ngrams. Renders each ngram, extracts spacing properties and records them in output_base/[font_name].fontinfo file.  (type:bool default:false)
  --output_individual_glyph_images  If true also outputs individual character images  (type:bool default:false)
  --fontconfig_refresh_cache  Does a one-time deletion of cache files from the fontconfig_tmpdir before initializing fontconfig.  (type:bool default:false)
  --fontconfig_refresh_config_file  Does a one-time reset of the fontconfig config file to point to fonts_dir before initializing fontconfig. Set to true if fontconfig_refresh_cache is true. Set it to false to use multiple instances in separate processes without having to rescan the fonts_dir, using a previously setup font cache  (type:bool default:true)
  --text  File name of text input to process  (type:string default:)
  --outputbase  Basename for output image/box file  (type:string default:)
  --writing_mode  Specify one of the following writing modes.
'horizontal' : Render regular horizontal text. (default)
'vertical' : Render vertical text. Glyph orientation is selected by Pango.
'vertical-upright' : Render vertical text. Glyph  orientation is set to be upright.  (type:string default:horizontal)
  --font  Font description name to use  (type:string default:Arial)
  --unicharset_file  File with characters in the unicharset. If --render_ngrams is true and --unicharset_file is specified, ngrams with characters that are not in unicharset will be omitted  (type:string default:)
  --fonts_dir  Overrides system default font location  (type:string default:/auto/ocr-data/tesstraining/fonts)
  --fontconfig_tmpdir  Overrides fontconfig default temporary dir  (type:string default:/tmp)

```

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ ./text2tif --list_available_fonts
Unable to open '/tmp/fonts.conf' for writing
  0: AR BERKLEY
  1: AR BLANCA
  2: AR BONNIE
  3: AR CARTER
  4: AR CENA
  5: AR CHRISTY
  6: AR DARLING
  7: AR DECODE
etc
```

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ ./text2tif --list_available_fonts --fontconfig_tmpdir ../temp
FcInitiReinitialize failed!!
  0: AR BERKLEY
  1: AR BLANCA
  2: AR BONNIE
  3: AR CARTER
  4: AR CENA
  5: AR CHRISTY
  6: AR DARLING
  7: AR DECODE
  8: AR DELANEY
  9: AR DESTINE
 10: AR ESSENCE
 11: AR HERMANN
 12: AR JULIAN
 13: Aksharyogini2
 14: Aparajita
etc
```

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --list_available_fonts
  0: AR BERKLEY
  1: AR BLANCA
  2: AR BONNIE
  3: AR CARTER
  4: AR CENA
  5: AR CHRISTY
  6: AR DARLING
  7: AR DECODE
etc
```

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/ara/ara.training_text --font FreeZerif --outputbase ara.FreeSerif.exp0
Could not find font named FreeZerif. Pango suggested font
Please correct '--font' arg.

```

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/ara/ara.training_text --outputbase ara.Arial.exp0
Segmentation fault

```

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/ara/ara.training_text --outputbase ara.Arial.exp0
Segmentation fault

ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/eng/eng.training_text --font Arial --outputbase eng.Arial.exp0
Segmentation fault

ra@Shree MINGW64 ~/text2tif
$ ls ../langdata/eng/eng.training_text
../langdata/eng/eng.training_text

```

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fontconfig_refresh_cache
'--text' option is missing!

ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/san/san.training_text --fontconfig_refresh_cache
'--outputbase' option is missing!

ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/san/san.training_text --fontconfig_refresh_cache --outputbase san.Arial.exp0
Segmentation fault

```

**Comment by Shreeshrii** [comment]
```
ra@Shree MINGW64 ~/text2tif
$ ./text2tif --fonts_dir= --text ../langdata/san/san.training_text --outputbase san.exp-1 --ptsize=32 --strip_unrenderable_words --fontconfig_refresh_config_file=false --leading=32 --char_spacing=0.0 --exposure=-1 --find_fonts --min_coverage=.9 --degrade_image=1 --underline_start_prob=.05 --underline_continuation_prob=.01
WARNING: Could not find a font to render image title with!
Total chars = 57894
Font AR BERKLEY failed with 8168 hits = 14.11%
Font AR BLANCA failed with 8168 hits = 14.11%
Font AR BONNIE failed with 8168 hits = 14.11%
Font AR CARTER failed with 8168 hits = 14.11%
Font AR CENA failed with 8168 hits = 14.11%
Font AR CHRISTY failed with 8168 hits = 14.11%
Font AR DARLING failed with 8168 hits = 14.11%
Font AR DECODE failed with 8168 hits = 14.11%
Font AR DELANEY failed with 8168 hits = 14.11%
Font AR DESTINE failed with 8168 hits = 14.11%
Font AR ESSENCE failed with 8168 hits = 14.11%
Font AR HERMANN failed with 8168 hits = 14.11%
Font AR JULIAN failed with 8168 hits = 14.11%
Font Aksharyogini2 failed with 8168 hits = 14.11%
Font Aparajita failed with 8168 hits = 14.11%
Font Aparajita Bold failed with 8168 hits = 14.11%
Font Aparajita Bold Italic failed with 8168 hits = 14.11%
Font Aparajita Italic failed with 8168 hits = 14.11%

```
WARNING: Could not find a font to render image title with!

But it is being treated as an error and the font files are listed but not processed - values are incorrect. Fonts with 100% coverage not being identified. 

Check the cygwin post for correct processing

**Comment by amitdo** [comment]
Please open new issues:
- Pango-CRITICAL **: pango_font_description_set_size: assertion 'size >= 0' failed
- 'ptsize' is not respected when '--find_fonts' and '--render_per_font' are used 
- ./text2tif --list_available_fonts

**Comment by Shreeshrii** [comment]
From: https://sourceforge.net/p/msys2/wiki/Contributing%20to%20MSYS2/

Some useful identifiers: (see webpage for better formatted list)

```
Identifier  Platform(s) Usage
_WIN32  mingw, msvc C code (#ifdef ...)
_WIN64  64-bit mingw, 64-bit msvc   C code (#ifdef ...)
__CYGWIN__  msys2, cygwin   C code (#ifdef ...)
__MSYS__    msys2   C code (#ifdef ...)
x86_64-pc-msys2 64-bit msys2    Build scripts (if [ $host = '...' ])
i686-pc-msys2   32-bit msys2    Build scripts (if [ $host = '...' ])
x86_64-w64-mingw32  64-bit mingw    Build scripts (if [ $host = '...' ])
i686-w64-mingw32    32-bit mingw    Build scripts (if [ $host = '...' ])
msys    msys2   Python (sys.platform)
win32   mingw   Python (sys.platform)
```
